
export const Aerobic = [ "BIKING", "RUNNING", "AEROBICS", "MOUNTAIN_BIKING", "ROAD_BIKING", "SPINNING", "STATIONARY_BIKING",
    "UTILITY_BIKING", "CALISTHENICS", "DANCING", "ELLIPTICAL", "FENCING", "FRISBEE",
    "GYMNASTICS", "HANDBALL", "HIKING", "HORSEBACK_RIDING", "JUMPING_ROPE", "KAYAKING", "KITESURFING"
    , "MEDITATION", "PARAGLIDING", "PILATES", "POLO", "RACQUETBALL", "ROCK_CLIMBING",
    "ROWING", "SAILING", "SCUBA_DIVING", "SKATEBOARDING", "SKATING", "INDOOR_ROLLERBLADING", "SQUASH", "STAIR_CLIMBING",
    "STAND_UP_PADDLEBOARDING", "SURFING", "SWIMMING", "SWIMMING_SWIMMING_POOL", "SWIMMING_OPEN_WATER",
    "NORDIC_WALKING", "WALKING_TREADMILL", "WATERPOLO", "WINDSURFING", "ZUMBA", "DIVING", "ICE_SKATING", "INDOOR_SKATING" ];

export const Anaerobic = [ "BIATHLON", "HANDBIKING", "SPRINTING", "KITE_SKIING", "ROLLER_SKIING",
    "SLEDDING", "SNOWBOARDING", "SNOWMOBILE", "SNOWSHOEING", "HIIT"];

export const Strength_Training = ["WEIGHTLIFTING", "KETTLEBELL_TRAINING", "ROWING", "ROWING_MACHINE", "STAIR_CLIMBING", "STAIR_CLIMBING_MACHINE",
    "PARAGLIDING", "ROCK_CLIMBING", "CROSSFIT", "INTERVAL_TRAINING", "CIRCUIT_TRAINING"];

export const YogAsanas = ["YOGA"];

export const Athletic_Training =  [ "BADMINTON", "BASEBALL", "BASKETBALL", "HOCKEY", "TENNIS", "TREADMILL", "VOLLEYBALL_BEACH", "VOLLEYBALL_INDOOR", "WAKEBOARDING", "WALKING_FITNESS",
    "TENNIS", "VOLLEYBALL","TEAM_SPORTS", "TABLE_TENNIS","KICKBOXING", "BOXING", "AMERICAN_FOOTBALL", "AUSTRALIAN_FOOTBALL",
    "MARTIAL_ARTS", "P90X_EXERCISES", "MIXED_MARTIAL_ARTS", "ENGLISH_FOOTBALL", "CRICKET", "RUGBY", "JOGGING", "RUNNING_ON_SAND", "TREADMILL_RUNNING"];

export const Other = ["STILL", "UNKNOWN", "TILTING", "WALKING", "HOUSEWORK", "WALKING_STROLLER", "ELEVATOR", "ESCALATOR", "ARCHERY", "SOFTBALL", "GARDENING",
    "GUIDED_BREATHING", "CURLING", "OTHER"];
