change-template: "* $TITLE (#$NUMBER) by @$AUTHOR"
name-template: '$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '⚡ Breaking Changes'
    labels:
      - 'breaking-change'
  - title: '🌟New features and non-breaking changes'
    labels:
      - 'Major'
      - 'feature'
  - title: '🌟 Minor Changes'
    labels:
      - 'enhancement'
  - title: '📜 Documentation updates'
    labels:
      - 'documentation'
  - title: '🐛 Bug and hot fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '🚒 Deprecations'
    labels:
      - 'deprecated'
  - title: '🔧 Maintenance'
    labels:
      - 'internal'
      - 'dependencies'
exclude-labels:
  - 'skip-changelog'
version-resolver:
  Major:
    labels:
      - 'Major'
  Minor:
    labels:
      - 'Minor'
  Patch:
    labels:
      - 'Patch'
  default: Major
template: |
  ## Summary

  ## Changes

  $CHANGES

  ## This release was made possible by the following contributors:

  $CONTRIBUTORS
