export enum OrganizationTypes {
    Clinic                            = 'Clinic',
    Hospital                          = 'Hospital',
    DiagnosticLab                     = 'Diagnostic Lab',
    DiagnosticLab_Pathology           = 'Diagnostic Lab - Pathology',
    DiagnosticLab_Imaging             = 'Diagnostic Lab - Imaging',
    Pharmacy                          = 'Pharmacy',
    AmbulanceService                  = 'Ambulance Service',
    GovernmentPrimaryHealthCareCentre = 'Government Primary Health Care Centre',
    GovernmentNodalHospital           = 'Government Nodal Hospital',
    GovernmentDistrictHospital        = 'Government District Hospital',
    MunicipalHospital                 = 'Municipal Hospital',
    BloodBank                         = 'Blood Bank',
    NursingHome                       = 'Nursing Home',
    SpecializedCareCentre             = 'Specialized Care Centre',
    AmbulatoryProcedureCentre         = 'Ambulatory Procedure Centre',
    SocialHealth                      = 'Social Health',
    Unknown                           = 'Unknown'
}

export const OrganizationTypeList: OrganizationTypes [] = [
    OrganizationTypes.Clinic,
    OrganizationTypes.Hospital,
    OrganizationTypes.DiagnosticLab,
    OrganizationTypes.DiagnosticLab_Pathology,
    OrganizationTypes.DiagnosticLab_Imaging,
    OrganizationTypes.Pharmacy,
    OrganizationTypes.AmbulanceService,
    OrganizationTypes.GovernmentPrimaryHealthCareCentre,
    OrganizationTypes.GovernmentNodalHospital,
    OrganizationTypes.GovernmentDistrictHospital,
    OrganizationTypes.MunicipalHospital,
    OrganizationTypes.BloodBank,
    OrganizationTypes.NursingHome,
    OrganizationTypes.SpecializedCareCentre,
    OrganizationTypes.AmbulatoryProcedureCentre,
    OrganizationTypes.SocialHealth,
    OrganizationTypes.Unknown,
];
