name: setup aws
description: "Config AWS"
inputs:
  image_tag:
    description: "AWS ECR image tag"
    required: false
  duplo_token:
    required: true
  task_def:
    required: true
  aws-region:
    required: true
  service_name:
    required: true
  duplocloud_token:
    required: true
  duplo_id:
    required: true
  tenant:
    required: true
    
runs:
  using: "composite"
  steps:
    - name: aws-jit
      uses: duplocloud/ghactions-aws-jit@master
      with:
        duplo_host: https://reanfoundation.duplocloud.net/
        duplo_token: ${{ inputs.duplo_token }}
        tenant: ${{ inputs.tenant }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
            ${{ runner.os }}-buildx-
    - name: Build
      id: docker_build
      uses: docker/build-push-action@v3
      with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.image_tag }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

    - name: Image digest
      shell: bash
      run: echo ${{ steps.docker_build.outputs.digest }}
    - name: Download task definition
      shell: bash
      run: |
        aws ecs describe-task-definition --task-definition ${{ inputs.task_def }} \
        --query taskDefinition > task-definition.json
        
    - name: New image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: default
        image: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.image_tag }}
        
    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        wait-for-service-stability: true
        
    - name: Task Definition Variable
      id: taskdefintionvar
      shell: bash
      run: |
        echo "task_definition_arn=$(aws ecs describe-task-definition --task-definition ${{ inputs.task_def }} | jq '.[] | .taskDefinitionArn')" >> $GITHUB_OUTPUT
        
    - name: Task Defintion ARN
      shell: bash
      run: |
        echo "Task Defintion: ${{ steps.taskdefintionvar.outputs.task_definition_arn }}"
        
    - name: Deploy Amazon ECS task definition using Duplo API
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://reanfoundation.duplocloud.net/subscriptions/${{ inputs.duplo_id }}/UpdateEcsService'
        method: 'POST'
        data: '{"TaskDefinition":${{ steps.taskdefintionvar.outputs.task_definition_arn }},"Name": "${{ inputs.service_name }}","Replicas":1, "HealthCheckGracePeriodSeconds": 1200}'
        bearerToken: ${{ inputs.duplocloud_token }}
