export enum MedicationTimeSchedules {
    Morning   = 'Morning',
    Afternoon = 'Afternoon',
    Evening   = 'Evening',
    Night     = 'Night',
    Custom    = 'Custom'
}

export const MedicationTimeSchedulesList: MedicationTimeSchedules [] = [
    MedicationTimeSchedules.Morning,
    MedicationTimeSchedules.Afternoon,
    MedicationTimeSchedules.Evening,
    MedicationTimeSchedules.Night,
    MedicationTimeSchedules.Custom,
];

export enum MedicationDosageUnits {
    Tablet             = 'Tablet',
    Capsule            = 'Capsule',
    Drop               = 'Drop',
    Tube               = 'Tube',
    MetricDrop         = 'Metric drop',
    Milligram          = 'Milligram',
    Milliliter         = 'Milliliter',
    Gram               = 'Gram',
    Microgram          = 'Microgram',
    Syringe            = 'Syringe',
    Spray              = 'Spray',
    Tablespoon         = 'Tablespoon',
    Teaspoon           = 'Teaspoon',
    Unit               = 'Unit',
    Nebulizer          = 'Nebulizer',
    Ampule             = 'Ampule(s)',
    Application        = 'Application',
    Bar                = 'Bar',
    BiscuitWafer       = 'Biscuit wafer',
    Can                = 'Can',
    Container          = 'Container',
    Enema              = 'Enema',
    Suppository        = 'Suppository',
    FluidOunce         = 'Fluid ounce',
    Gallon             = 'Gallon',
    Gum                = 'Gum',
    Inch               = 'Inch',
    InternationalUnits = 'International units',
    Kilogram           = 'Kilogram',
    Liter              = 'Liter',
    Lozenge            = 'Lozenge',
    Milliequivalent    = 'Milliequivalent',
    MilligramPerSqMtr  = 'Milligram per meter squared',
    MillionUnits       = 'Million units',
    Pad                = 'Pad',
    Patch              = 'Patch',
    Pint               = 'Pint',
    Puff               = 'Puff',
    RingPessary        = 'Ring pessary',
    Scoopful           = 'Scoopful',
    Vial               = 'Vial',
}

export const MedicationDosageUnitsList: MedicationDosageUnits [] = [
    MedicationDosageUnits.Tablet,
    MedicationDosageUnits.Capsule,
    MedicationDosageUnits.Drop,
    MedicationDosageUnits.Tube,
    MedicationDosageUnits.MetricDrop,
    MedicationDosageUnits.Milligram,
    MedicationDosageUnits.Milliliter,
    MedicationDosageUnits.Gram,
    MedicationDosageUnits.Microgram,
    MedicationDosageUnits.Syringe,
    MedicationDosageUnits.Spray,
    MedicationDosageUnits.Tablespoon,
    MedicationDosageUnits.Teaspoon,
    MedicationDosageUnits.Unit,
    MedicationDosageUnits.Nebulizer,
    MedicationDosageUnits.Ampule,
    MedicationDosageUnits.Application,
    MedicationDosageUnits.Bar,
    MedicationDosageUnits.BiscuitWafer,
    MedicationDosageUnits.Can,
    MedicationDosageUnits.Container,
    MedicationDosageUnits.Enema,
    MedicationDosageUnits.Suppository,
    MedicationDosageUnits.FluidOunce,
    MedicationDosageUnits.Gallon,
    MedicationDosageUnits.Gum,
    MedicationDosageUnits.Inch,
    MedicationDosageUnits.InternationalUnits ,
    MedicationDosageUnits.Kilogram,
    MedicationDosageUnits.Liter,
    MedicationDosageUnits.Lozenge,
    MedicationDosageUnits.Milliequivalent,
    MedicationDosageUnits.MilligramPerSqMtr,
    MedicationDosageUnits.MillionUnits,
    MedicationDosageUnits.Pad,
    MedicationDosageUnits.Patch,
    MedicationDosageUnits.Pint,
    MedicationDosageUnits.Puff,
    MedicationDosageUnits.RingPessary,
    MedicationDosageUnits.Scoopful,
    MedicationDosageUnits.Vial
];

export enum MedicationDurationUnits {
    Months         = 'Months',
    Weeks          = 'Weeks',
    Days           = 'Days',
    Years          = 'Years',
    Minutes        = 'Minutes',
    Hours          = 'Hours',
    NumOccurrences = 'Number of occurrences',
    Seconds        = 'Seconds',
}

export const MedicationDurationUnitsList: MedicationDurationUnits [] = [
    MedicationDurationUnits.Months,
    MedicationDurationUnits.Weeks,
    MedicationDurationUnits.Days,
    MedicationDurationUnits.Years,
    MedicationDurationUnits.Minutes,
    MedicationDurationUnits.Hours,
    MedicationDurationUnits.NumOccurrences,
    MedicationDurationUnits.Seconds,
];

export enum MedicationAdministrationRoutes {
    Oral          = 'Oral',
    Intravenous   = 'Intravenous',
    Intramuscular = 'Intramuscular',
    Subcutaneous  = 'Subcutaneous',
    Inhalation    = 'Inhalation',
    Intranasal    = 'Intranasal',
    InLeftEar     = 'In left ear',
    InRightEar    = 'In right ear',
    InBothEars    = 'In both ears',
    InLeftEye     = 'In left eye',
    InRightEye    = 'In right eye',
    InBothEyes    = 'In both eyes',
    Transdermal   = 'Transdermal',
    Vaginally     = 'Vaginally',
    Rectally      = 'Rectally',
    PerNGTube     = 'Per NG tube',
    Intraosseous  = 'Intraosseous',
}

export const MedicationAdministrationRoutesList: MedicationAdministrationRoutes [] = [
    MedicationAdministrationRoutes.Oral,
    MedicationAdministrationRoutes.Intravenous,
    MedicationAdministrationRoutes.Intramuscular,
    MedicationAdministrationRoutes.Subcutaneous,
    MedicationAdministrationRoutes.Inhalation,
    MedicationAdministrationRoutes.Intranasal,
    MedicationAdministrationRoutes.InLeftEar,
    MedicationAdministrationRoutes.InRightEar,
    MedicationAdministrationRoutes.InBothEars,
    MedicationAdministrationRoutes.InLeftEye,
    MedicationAdministrationRoutes.InRightEye,
    MedicationAdministrationRoutes.InBothEyes,
    MedicationAdministrationRoutes.Transdermal,
    MedicationAdministrationRoutes.Vaginally,
    MedicationAdministrationRoutes.Rectally,
    MedicationAdministrationRoutes.PerNGTube,
    MedicationAdministrationRoutes.Intraosseous,
];

export enum MedicationFrequencyUnits {
    Daily   = 'Daily',
    Weekly  = 'Weekly',
    Monthly = 'Monthly',
    Other   = 'Other'
}

export const MedicationFrequencyUnitsList: MedicationFrequencyUnits [] = [
    MedicationFrequencyUnits.Daily,
    MedicationFrequencyUnits.Weekly,
    MedicationFrequencyUnits.Monthly,
    MedicationFrequencyUnits.Other
];
