export enum UserEngagementCategories {
    Overall     = 'Overall',
    Nutrition   = 'Nutrition',
    Medication  = 'Medication',
    Careplan    = 'Careplan',
    Assessment  = 'Assessment',
    Exercise    = 'Exercise',
    Vitals      = 'Vitals',
    LabRecords  = 'LabRecords',
    Symptom     = 'Symptom',
    Educational = 'Educational',
    Chat        = 'Chat',
    Appointment = 'Appointment',
    Task        = 'Task',
    Goal        = 'Goal',
    Newsfeed    = 'Newsfeed',
    Profile     = 'Profile',
    Notice      = 'Notice',
    Form        = 'Form',
    Survey      = 'Survey',
}

export const UserEngagementCategoryList: UserEngagementCategories[] = [
    UserEngagementCategories.Overall,
    UserEngagementCategories.Nutrition,
    UserEngagementCategories.Medication,
    UserEngagementCategories.Careplan,
    UserEngagementCategories.Assessment,
    UserEngagementCategories.Exercise,
    UserEngagementCategories.Vitals,
    UserEngagementCategories.LabRecords,
    UserEngagementCategories.Symptom,
    UserEngagementCategories.Educational,
    UserEngagementCategories.Chat,
    UserEngagementCategories.Appointment,
    UserEngagementCategories.Task,
    UserEngagementCategories.Goal,
    UserEngagementCategories.Newsfeed,
    UserEngagementCategories.Profile,
    UserEngagementCategories.Notice,
    UserEngagementCategories.Form,
    UserEngagementCategories.Survey,
];
