
export enum UserTaskCategory {
    Medication            = 'Medication',
    Appointment           = 'Appointment',
    Educational           = 'Educational',
    Exercise              = 'Exercise',
    Nutrition             = 'Nutrition',
    Biometrics            = 'Biometrics',
    FitnessRecord         = 'Fitness record',
    ClinicalAssessment    = 'Clinical assessment',
    StressManagement      = 'Stress management',
    Challenge             = 'Challenge',
    CarePlanGoal          = 'Care plan - goal',
    CarePlanGoalSetting   = 'Care plan - goal setting',
    ConsultationCall      = 'Consultation - call',
    ConsultationMessage   = 'Consultation - message',
    ConsultationTeleVisit = 'Consultation - televisit',
    PersonalReflection    = 'Personal reflection',
    Custom                = 'Custom',
}

export const UserTaskCategoryList: UserTaskCategory [] = [
    UserTaskCategory.Medication,
    UserTaskCategory.Appointment,
    UserTaskCategory.Educational,
    UserTaskCategory.Exercise,
    UserTaskCategory.Nutrition,
    UserTaskCategory.Biometrics,
    UserTaskCategory.FitnessRecord,
    UserTaskCategory.ClinicalAssessment,
    UserTaskCategory.StressManagement,
    UserTaskCategory.Challenge,
    UserTaskCategory.CarePlanGoal,
    UserTaskCategory.CarePlanGoalSetting,
    UserTaskCategory.ConsultationCall,
    UserTaskCategory.ConsultationMessage,
    UserTaskCategory.ConsultationTeleVisit,
    UserTaskCategory.PersonalReflection,
    UserTaskCategory.Custom,
];
