
export enum HealthPriorityType {
    PhysicalActivity      = 'Physical Activity',
    Nutrition             = 'Nutrition',
    Weight                = 'Weight',
    Tobacco               = 'Tobacco',
    BloodPressure         = 'Blood Pressure',
    Cholesterol           = 'Cholesterol',
    Glucose               = 'Glucose',
    Medications           = 'Medications',
    MentalHealth          = 'Mental Health',
    LifesSimple7          = 'Lifes Simple 7',
    ChildhoodObesity      = 'Childhood Obesity',
    Professional          = 'Professional',
    Planning              = 'Planning',
    Support               = 'Support',
    Stress                = 'Stress',
    Depression            = 'Depression',
    Anxiety               = 'Anxiety',
    Heartfailure          = 'Heart failure',
    Atrialfibrillation    = 'Atrial fibrillation',
    Stroke                = 'Stroke',
    Cardiacrehabilitation = 'Cardiac rehabilitation',
    Coronaryarterydisease = 'Coronary artery disease',
    Sodium                = 'Sodium',
    Fat                   = 'Fat',
    Carbohydrates         = 'Carbohydrates',

}

export const HealthPriorityTypeList: HealthPriorityType [] = [
    HealthPriorityType.PhysicalActivity,
    HealthPriorityType.Nutrition,
    HealthPriorityType.Weight,
    HealthPriorityType.Tobacco,
    HealthPriorityType.BloodPressure,
    HealthPriorityType.Cholesterol,
    HealthPriorityType.Glucose,
    HealthPriorityType.Medications,
    HealthPriorityType.MentalHealth,
    HealthPriorityType.LifesSimple7,
    HealthPriorityType.ChildhoodObesity,
    HealthPriorityType.Professional,
    HealthPriorityType.Planning,
    HealthPriorityType.Support,
    HealthPriorityType.Stress,
    HealthPriorityType.Depression,
    HealthPriorityType.Anxiety,
    HealthPriorityType.Heartfailure,
    HealthPriorityType.Atrialfibrillation,
    HealthPriorityType.Stroke,
    HealthPriorityType.Cardiacrehabilitation,
    HealthPriorityType.Coronaryarterydisease,
    HealthPriorityType.Sodium,
    HealthPriorityType.Fat,
    HealthPriorityType.Carbohydrates,
];
