name: Deploy on Azure Container App

on:
  push:
    branches:
      - develop-azure

jobs:
  build:
    environment: dev-azure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        run: |
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ secrets.REGISTRY_SERVER }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az --version

      - name: Azure Login
        run: az login --service-principal --username ${{ secrets.AZURE_APP_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      # - name: Copy env file
      #   run: |
      #     touch .env
      #     az storage blob download --file ./.env --container-name ${{ secrets.CONTAINER_NAME }} --name ${{ secrets.BLOB_NAME }} --account-name ${{ secrets.ACCOUNT_NAME }} --account-key ${{ secrets.ACCOUNT_KEY }}
      #     ls -a

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY_SERVER }}/reancare-service:${{ github.sha }}

  deploy:
    environment: dev-azure
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Login to Azure Container Apps
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az --version

      - name: Azure Login
        run: az login --service-principal --username ${{ secrets.AZURE_APP_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Deploy to Azure Container Apps
        run: az containerapp update --name reancare-service-dev --resource-group dev-resource-group --image ${{ secrets.REGISTRY_SERVER }}/reancare-service:${{ github.sha }} --min-replicas 1 --max-replicas 2

